#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 07, 2018 11:09:43 PM


import sys
import platform
import os
from os.path import join,getsize,exists


try:
    from Tkinter import *
    import tkMessageBox
    import tkFont
    import tkFileDialog
except ImportError:
    from tkinter import *
    from tkinter import messagebox
    from tkinter import font
    from tkinter import filedialog

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True



def btnExit_LeftClick(p1):
    print('unknown_support.btnExit_LeftClick')
    sys.stdout.flush()
    destroy_window()

class btn(object):

    def __init__(self):
        self.res = None

    @classmethod
    def btnSel_LeftClick(self,p1):
        from tkinter import filedialog
        print('unknown_support.btnSel_LeftClick')
        sys.stdout.flush()
        self.res = filedialog.askopenfilename(initialdir = "/",title = "Select file",filetypes = (("wav files","*.wav"),("all files","*.*")))
        print(self.res)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import unknown
    unknown.vp_start_gui()


