#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    Jun 07, 2018 11:09:43 PM


import sys

try:
    from Tkinter import *
    from tkinter import filedialog
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def btnExit_LeftClick(p1):
    print('unknown_support.btnExit_LeftClick')
    sys.stdout.flush()
    destroy_window()

def btnSel_LeftClick(p1):
    from tkinter import filedialog
    print('unknown_support.btnSel_LeftClick')
    sys.stdout.flush()
    res = filedialog.askopenfilename(initialdir = "/",title = "Select file",filetypes = (("wav files","*.wav"),("all files","*.*")))
    print(res)


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import unknown
    unknown.vp_start_gui()


